# Generated by Django 4.2.2 on 2025-03-23 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("games", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="interaction",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="games",
            name="developer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="games.developer"
            ),
        ),
        migrations.AddField(
            model_name="games",
            name="genre",
            field=models.ManyToManyField(related_name="games", to="games.genre"),
        ),
    ]
